runtime: nodejs12
service: orders

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 1
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50
